spring:
  datasource:
    url: jdbc:h2:mem:store
    username: sa
    password: password
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        generate_statistics: false
  liquibase:
    enabled: true
    changeLog: classpath:/db/db.changelog.xml
